In [2]:
import numpy as np
import pandas as pd

In [4]:
# load data
df = pd.read_pickle("./dataset.pkl")

In [6]:
df["length"] = df["sequence"].str.len()

In [7]:
# run this if working with subset of dataset
df = df[df['length'] <= 500].head(10000)

In [48]:
# pad sequences and lists

def pad_list(tensor_list, max_len):
    return tensor_list + [None] * (max_len - len(tensor_list))

def pad_sequence(sequence, max_len):
    return sequence + "-"*(max_len - len(sequence))


df["padded_pfam_tensor"] = df["pfam_tensor"].apply(
    lambda x: pad_list(x, 500)
)

df["padded_sequence"] = df["sequence"].apply(
    lambda x: pad_sequence(x, 500)
)

df

,pfam_tensor,sequence,length,padded_pfam_tensor,padded_seuqence,pfam_oh_index,padded_sequence
A1AL94,"[None, None, None, None, None, None, None, Non...",MSLTTLVTQQAPDFTAEAVMADNSFASITLSSLKGKFVLLLFYPLD...,198,"[None, None, None, None, None, None, None, Non...",MSLTTLVTQQAPDFTAEAVMADNSFASITLSSLKGKFVLLLFYPLD...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",MSLTTLVTQQAPDFTAEAVMADNSFASITLSSLKGKFVLLLFYPLD...
A0A0F7V1V9,"[None, None, None, None, None, None, None, Non...",MAACLRAARLSLRQMEGLIEPSVRGRSSPLSMVRLLPSSSVSSSSP...,283,"[None, None, None, None, None, None, None, Non...",MAACLRAARLSLRQMEGLIEPSVRGRSSPLSMVRLLPSSSVSSSSP...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",MAACLRAARLSLRQMEGLIEPSVRGRSSPLSMVRLLPSSSVSSSSP...
Q4UGC8,"[None, None, None, None, None, None, None, Non...",MKLTGISLISSLSYIRNTLPLKNTLTAFHTLNTRNNLKSVNRITSV...,261,"[None, None, None, None, None, None, None, Non...",MKLTGISLISSLSYIRNTLPLKNTLTAFHTLNTRNNLKSVNRITSV...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",MKLTGISLISSLSYIRNTLPLKNTLTAFHTLNTRNNLKSVNRITSV...
A4H879,"[None, None, None, None, None, None, None, Non...",MSCGDAKMNEPAPPFEEMALMPNGSFKKINLASYKGKWVVLFFYPL...,199,"[None, None, None, None, None, None, None, Non...",MSCGDAKMNEPAPPFEEMALMPNGSFKKINLASYKGKWVVLFFYPL...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",MSCGDAKMNEPAPPFEEMALMPNGSFKKINLASYKGKWVVLFFYPL...
A0A0M5IXP6,"[None, None, None, None, None, None, None, Non...",MNPSANESGVCSPVQIGDAAPNFQARTTLGEMSLSDYRGRWVLLFS...,221,"[None, None, None, None, None, None, None, Non...",MNPSANESGVCSPVQIGDAAPNFQARTTLGEMSLSDYRGRWVLLFS...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",MNPSANESGVCSPVQIGDAAPNFQARTTLGEMSLSDYRGRWVLLFS...
...,...,...,...,...,...,...,...
Q9A6W1,"[None, None, None, None, None, None, None, Non...",MAQAERPSASRLVAIATERHLIMKNPDSRRGRKDRRKEPRYQVKRR...,210,"[None, None, None, None, None, None, None, Non...",MAQAERPSASRLVAIATERHLIMKNPDSRRGRKDRRKEPRYQVKRR...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",MAQAERPSASRLVAIATERHLIMKNPDSRRGRKDRRKEPRYQVKRR...
A9WHE0,"[PF03992.22, PF03992.22, PF03992.22, PF03992.2...",MYGLIGKMRATPGQRDALIAILVEGASSMPGCLSYVVAQDPKDPDA...,100,"[PF03992.22, PF03992.22, PF03992.22, PF03992.2...",MYGLIGKMRATPGQRDALIAILVEGASSMPGCLSYVVAQDPKDPDA...,"[166, 166, 166, 166, 166, 166, 166, 166, 166, ...",MYGLIGKMRATPGQRDALIAILVEGASSMPGCLSYVVAQDPKDPDA...
Q8Y824,"[None, None, None, PF03992.22, PF03992.22, PF0...",MKVGYGLLTAFYTHPGERDHLVKILLEAAESLEEYNTCIQYIVSES...,102,"[None, None, None, PF03992.22, PF03992.22, PF0...",MKVGYGLLTAFYTHPGERDHLVKILLEAAESLEEYNTCIQYIVSES...,"[0, 0, 0, 166, 166, 166, 166, 166, 166, 166, 1...",MKVGYGLLTAFYTHPGERDHLVKILLEAAESLEEYNTCIQYIVSES...
Q9ZBJ4,"[None, PF03992.22, PF03992.22, PF03992.22, PF0...",MTYGCIASMKTRPGFREEVVSLLLSAADGLRDAGCELYVVGLSEDD...,99,"[None, PF03992.22, PF03992.22, PF03992.22, PF0...",MTYGCIASMKTRPGFREEVVSLLLSAADGLRDAGCELYVVGLSEDD...,"[0, 166, 166, 166, 166, 166, 166, 166, 166, 16...",MTYGCIASMKTRPGFREEVVSLLLSAADGLRDAGCELYVVGLSEDD...
Q9RSM4,"[None, None, None, None, None, None, None, Non...",MSPQSMLTSPQHPRRTTMVISHGTLSASAEHAAHLRQLLVHIAQAT...,118,"[None, None, None, None, None, None, None, Non...",MSPQSMLTSPQHPRRTTMVISHGTLSASAEHAAHLRQLLVHIAQAT...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",MSPQSMLTSPQHPRRTTMVISHGTLSASAEHAAHLRQLLVHIAQAT...

In [33]:
# one hot encode both sequences and lists


unique_pfams = set()
for pfam in df['padded_pfam_tensor'].values:
    unique_pfams.update(pfam)

unique_pfams = list(unique_pfams)

unique_pfams.remove(None)
unique_pfams.insert(0, None)

unique_pfams

[None,
 'PF08521.16',
 'PF04463.17',
 'PF02175.22',
 'PF23313.1',
 'PF13245.12',
 'PF13661.12',
 'PF07885.22',
 'PF10317.15',
 'PF23143.1',
 'PF22546.2',
 'PF05761.20',
 'PF13339.11',
 'PF23242.1',
 'PF00696.33',
 'PF22990.1',
 'PF25408.1',
 'PF10324.15',
 'PF13532.12',
 'PF10321.15',
 'PF03886.18',
 'PF08164.17',
 'PF21964.2',
 'PF14253.11',
 'PF01471.23',
 'PF02949.25',
 'PF14934.11',
 'PF13346.12',
 'PF10322.15',
 'PF23021.3',
 'PF25361.1',
 'PF18865.6',
 'PF07562.20',
 'PF02254.24',
 'PF06182.17',
 'PF06541.16',
 'PF13401.12',
 'PF15420.11',
 'PF10899.13',
 'PF03491.18',
 'PF00005.33',
 'PF16450.11',
 'PF13555.12',
 'PF01257.25',
 'PF00950.22',
 'PF06983.19',
 'PF14156.11',
 'PF07696.17',
 'PF13479.12',
 'PF14510.11',
 'PF16873.10',
 'PF08336.16',
 'PF20265.3',
 'PF16182.10',
 'PF00578.27',
 'PF08793.15',
 'PF06439.18',
 'PF09206.18',
 'PF00364.28',
 'PF12430.13',
 'PF00708.24',
 'PF13476.12',
 'PF21707.3',
 'PF01061.29',
 'PF00900.26',
 'PF04083.22',
 'PF03061.28',
 'PF01288.25',
 'PF20515.4',
 'PF13238.12',
 'PF21734.3',
 'PF03171.26',
 'PF10319.15',
 'PF01877.22',
 'PF13304.12',
 'PF06052.18',
 'PF13481.12',
 'PF07726.17',
 'PF13649.12',
 'PF17871.7',
 'PF17194.10',
 'PF07815.19',
 'PF01812.26',
 'PF13853.12',
 'PF00467.35',
 'PF07694.17',
 'PF21639.3',
 'PF24792.1',
 'PF08975.16',
 'PF10417.14',
 'PF03390.20',
 'PF00207.28',
 'PF00561.26',
 'PF03446.21',
 'PF22624.1',
 'PF25158.1',
 'PF06684.16',
 'PF23357.1',
 'PF18863.6',
 'PF23900.1',
 'PF02117.22',
 'PF07698.17',
 'PF12729.13',
 'PF18524.6',
 'PF13500.12',
 'PF21396.3',
 'PF20789.3',
 'PF08395.17',
 'PF02152.23',
 'PF07751.16',
 'PF22951.1',
 'PF04029.19',
 'PF14337.12',
 'PF10328.15',
 'PF05635.17',
 'PF08071.17',
 'PF22316.2',
 'PF17837.6',
 'PF10292.15',
 'PF00004.35',
 'PF13635.12',
 'PF02817.22',
 'PF09336.16',
 'PF06189.17',
 'PF01073.25',
 'PF08349.16',
 'PF07677.20',
 'PF02096.25',
 'PF11591.13',
 'PF16998.10',
 'PF18671.6',
 'PF20981.2',
 'PF17028.10',
 'PF13173.12',
 'PF01966.28',
 'PF03109.22',
 'PF13671.12',
 'PF24358.1',
 'PF10325.15',
 'PF09822.16',
 'PF24526.1',
 'PF14363.11',
 'PF11706.13',
 'PF13239.11',
 'PF10323.15',
 'PF13614.12',
 'PF16121.10',
 'PF12476.13',
 'PF25221.1',
 'PF00734.23',
 'PF09819.14',
 'PF13604.12',
 'PF03417.21',
 'PF13427.11',
 'PF00393.24',
 'PF07388.17',
 'PF13191.12',
 'PF05270.19',
 'PF22547.2',
 'PF06725.17',
 'PF12002.13',
 'PF13748.11',
 'PF00198.28',
 'PF13759.12',
 'PF17864.7',
 'PF20446.3',
 'PF03992.22',
 'PF21584.2',
 'PF10318.15',
 'PF00244.26',
 'PF03562.22',
 'PF12775.13',
 'PF08279.18',
 'PF01367.25',
 'PF25426.1',
 'PF08792.16',
 'PF16326.10',
 'PF16078.10',
 'PF01478.23',
 'PF00001.26',
 'PF18321.7',
 'PF18860.6',
 'PF04392.18',
 'PF17863.7',
 'PF09847.15',
 'PF08740.16',
 'PF07695.17',
 'PF21709.3',
 'PF12407.13',
 'PF02230.22',
 'PF18225.7',
 'PF07142.17',
 'PF13087.12',
 'PF06580.19',
 'PF06480.20',
 'PF22242.1',
 'PF07966.17',
 'PF09818.15',
 'PF14226.12',
 'PF03443.20',
 'PF07728.20',
 'PF01490.24',
 'PF13338.12',
 'PF17866.7',
 'PF09407.15',
 'PF24838.2',
 'PF13279.12',
 'PF23232.1',
 'PF08843.17',
 'PF13840.12',
 'PF10320.15',
 'PF12679.13',
 'PF20091.5',
 'PF16122.10',
 'PF23022.3',
 'PF00002.29',
 'PF04476.19',
 'PF17862.7',
 'PF20150.5',
 'PF05496.18',
 'PF23563.1',
 'PF09952.14',
 'PF20408.4',
 'PF01909.29',
 'PF10637.15',
 'PF02739.22',
 'PF13521.12',
 'PF12537.13',
 'PF01479.30',
 'PF12695.13',
 'PF00389.36',
 'PF07336.16',
 'PF12698.13',
 'PF02737.24',
 'PF14108.11',
 'PF00324.27',
 'PF10327.15',
 'PF01591.24',
 'PF00003.28',
 'PF00725.27',
 'PF13622.12',
 'PF09821.14',
 'PF07247.17',
 'PF02496.21',
 'PF12592.13',
 'PF23902.1',
 'PF03306.18',
 'PF11459.13',
 'PF13302.13',
 'PF13872.12',
 'PF16193.11',
 'PF22468.2',
 'PF13520.12',
 'PF09752.15',
 'PF13906.12',
 'PF14400.11',
 'PF07859.19',
 'PF10316.15',
 'PF14355.11',
 'PF13640.12',
 'PF10014.15',
 'PF07501.17',
 'PF02829.19',
 'PF05282.17',
 'PF10081.15',
 'PF18331.6',
 'PF07724.20',
 'PF22227.1',
 'PF00156.33',
 'PF12715.13',
 'PF07703.20',
 'PF17868.7',
 'PF14402.11',
 'PF10326.15',
 'PF13175.12',
 'PF21631.3',
 'PF09820.16',
 'PF03990.20',
 'PF05902.18',
 'PF22545.2',
 'PF21432.3',
 'PF06750.18',
 'PF08386.16',
 'PF12730.13',
 'PF06259.18',
 'PF02872.23',
 'PF02826.25',
 'PF02209.24',
 'PF13207.12',
 'PF08142.18',
 'PF14630.12',
 'PF18864.6',
 'PF14516.12',
 'PF12697.13',
 'PF13563.12',
 'PF04947.19']

In [50]:
PROTEIN_ALPHABET = {
    '-': 0,
    'A': 1,
    'C': 2,
    'D': 3,
    'E': 4,
    'F': 5,
    'G': 6,
    'H': 7,
    'I': 8,
    'K': 9,
    'L': 10,
    'M': 11,
    'N': 12,
    'P': 13,
    'Q': 14,
    'R': 15,
    'S': 16,
    'T': 17,
    'V': 18,
    'W': 19,
    'Y': 20,
    'X': 21
}

In [51]:
def one_hot_pfam(pfam_list):
    return [unique_pfams.index(pfam) for pfam in pfam_list]

def one_hot_sequence(sequence):
    return [PROTEIN_ALPHABET[aa] for aa in sequence]


df["pfam_oh_index"] = df["padded_pfam_tensor"].apply(
    lambda x: one_hot_pfam(x)
)

df["sequence_oh_index"] = df["padded_sequence"].apply(
    lambda x: one_hot_sequence(x)
)

df

,pfam_tensor,sequence,length,padded_pfam_tensor,padded_seuqence,pfam_oh_index,padded_sequence,sequence_oh_index
A1AL94,"[None, None, None, None, None, None, None, Non...",MSLTTLVTQQAPDFTAEAVMADNSFASITLSSLKGKFVLLLFYPLD...,198,"[None, None, None, None, None, None, None, Non...",MSLTTLVTQQAPDFTAEAVMADNSFASITLSSLKGKFVLLLFYPLD...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",MSLTTLVTQQAPDFTAEAVMADNSFASITLSSLKGKFVLLLFYPLD...,"[11, 16, 10, 17, 17, 10, 18, 17, 14, 14, 1, 13..."
A0A0F7V1V9,"[None, None, None, None, None, None, None, Non...",MAACLRAARLSLRQMEGLIEPSVRGRSSPLSMVRLLPSSSVSSSSP...,283,"[None, None, None, None, None, None, None, Non...",MAACLRAARLSLRQMEGLIEPSVRGRSSPLSMVRLLPSSSVSSSSP...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",MAACLRAARLSLRQMEGLIEPSVRGRSSPLSMVRLLPSSSVSSSSP...,"[11, 1, 1, 2, 10, 15, 1, 1, 15, 10, 16, 10, 15..."
Q4UGC8,"[None, None, None, None, None, None, None, Non...",MKLTGISLISSLSYIRNTLPLKNTLTAFHTLNTRNNLKSVNRITSV...,261,"[None, None, None, None, None, None, None, Non...",MKLTGISLISSLSYIRNTLPLKNTLTAFHTLNTRNNLKSVNRITSV...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",MKLTGISLISSLSYIRNTLPLKNTLTAFHTLNTRNNLKSVNRITSV...,"[11, 9, 10, 17, 6, 8, 16, 10, 8, 16, 16, 10, 1..."
A4H879,"[None, None, None, None, None, None, None, Non...",MSCGDAKMNEPAPPFEEMALMPNGSFKKINLASYKGKWVVLFFYPL...,199,"[None, None, None, None, None, None, None, Non...",MSCGDAKMNEPAPPFEEMALMPNGSFKKINLASYKGKWVVLFFYPL...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",MSCGDAKMNEPAPPFEEMALMPNGSFKKINLASYKGKWVVLFFYPL...,"[11, 16, 2, 6, 3, 1, 9, 11, 12, 4, 13, 1, 13, ..."
A0A0M5IXP6,"[None, None, None, None, None, None, None, Non...",MNPSANESGVCSPVQIGDAAPNFQARTTLGEMSLSDYRGRWVLLFS...,221,"[None, None, None, None, None, None, None, Non...",MNPSANESGVCSPVQIGDAAPNFQARTTLGEMSLSDYRGRWVLLFS...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",MNPSANESGVCSPVQIGDAAPNFQARTTLGEMSLSDYRGRWVLLFS...,"[11, 12, 13, 16, 1, 12, 4, 16, 6, 18, 2, 16, 1..."
...,...,...,...,...,...,...,...,...
Q9A6W1,"[None, None, None, None, None, None, None, Non...",MAQAERPSASRLVAIATERHLIMKNPDSRRGRKDRRKEPRYQVKRR...,210,"[None, None, None, None, None, None, None, Non...",MAQAERPSASRLVAIATERHLIMKNPDSRRGRKDRRKEPRYQVKRR...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",MAQAERPSASRLVAIATERHLIMKNPDSRRGRKDRRKEPRYQVKRR...,"[11, 1, 14, 1, 4, 15, 13, 16, 1, 16, 15, 10, 1..."
A9WHE0,"[PF03992.22, PF03992.22, PF03992.22, PF03992.2...",MYGLIGKMRATPGQRDALIAILVEGASSMPGCLSYVVAQDPKDPDA...,100,"[PF03992.22, PF03992.22, PF03992.22, PF03992.2...",MYGLIGKMRATPGQRDALIAILVEGASSMPGCLSYVVAQDPKDPDA...,"[166, 166, 166, 166, 166, 166, 166, 166, 166, ...",MYGLIGKMRATPGQRDALIAILVEGASSMPGCLSYVVAQDPKDPDA...,"[11, 20, 6, 10, 8, 6, 9, 11, 15, 1, 17, 13, 6,..."
Q8Y824,"[None, None, None, PF03992.22, PF03992.22, PF0...",MKVGYGLLTAFYTHPGERDHLVKILLEAAESLEEYNTCIQYIVSES...,102,"[None, None, None, PF03992.22, PF03992.22, PF0...",MKVGYGLLTAFYTHPGERDHLVKILLEAAESLEEYNTCIQYIVSES...,"[0, 0, 0, 166, 166, 166, 166, 166, 166, 166, 1...",MKVGYGLLTAFYTHPGERDHLVKILLEAAESLEEYNTCIQYIVSES...,"[11, 9, 18, 6, 20, 6, 10, 10, 17, 1, 5, 20, 17..."
Q9ZBJ4,"[None, PF03992.22, PF03992.22, PF03992.22, PF0...",MTYGCIASMKTRPGFREEVVSLLLSAADGLRDAGCELYVVGLSEDD...,99,"[None, PF03992.22, PF03992.22, PF03992.22, PF0...",MTYGCIASMKTRPGFREEVVSLLLSAADGLRDAGCELYVVGLSEDD...,"[0, 166, 166, 166, 166, 166, 166, 166, 166, 16...",MTYGCIASMKTRPGFREEVVSLLLSAADGLRDAGCELYVVGLSEDD...,"[11, 17, 20, 6, 2, 8, 1, 16, 11, 9, 17, 15, 13..."
Q9RSM4,"[None, None, None, None, None, None, None, Non...",MSPQSMLTSPQHPRRTTMVISHGTLSASAEHAAHLRQLLVHIAQAT...,118,"[None, None, None, None, None, None, None, Non...",MSPQSMLTSPQHPRRTTMVISHGTLSASAEHAAHLRQLLVHIAQAT...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",MSPQSMLTSPQHPRRTTMVISHGTLSASAEHAAHLRQLLVHIAQAT...,"[11, 16, 13, 14, 16, 11, 10, 17, 16, 13, 14, 7..."

In [40]:
def one_hot(indices, one_hot_len):
    vec = np.zeros(one_hot_len, dtype=int)
    vec[indices] = 1
    return vec

/tmp/ipykernel_250136/1686874206.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  list(df["pfam_oh_index"][1])

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 54,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 89,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]