In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
# %reload model

# from model import model_parts as mp
from model import ProtENN2_style

In [7]:
import numpy as np
import torch

model = ProtENN2_style()

test_input = torch.rand(64, 100, 21)

output = model(test_input)

In [4]:
print(output.shape)

print(torch.sum(output, axis=-1).shape)

torch.Size([64, 100, 628])
torch.Size([64, 100])

In [3]:
import pandas as pd

dataset_df = pd.read_pickle("../../dataset/dataset.pkl")  
dataset_df

,pfam_tensor,sequence
A1AL94,"[None, None, None, None, None, None, None, Non...",MSLTTLVTQQAPDFTAEAVMADNSFASITLSSLKGKFVLLLFYPLD...
A0A0F7V1V9,"[None, None, None, None, None, None, None, Non...",MAACLRAARLSLRQMEGLIEPSVRGRSSPLSMVRLLPSSSVSSSSP...
Q4UGC8,"[None, None, None, None, None, None, None, Non...",MKLTGISLISSLSYIRNTLPLKNTLTAFHTLNTRNNLKSVNRITSV...
A4H879,"[None, None, None, None, None, None, None, Non...",MSCGDAKMNEPAPPFEEMALMPNGSFKKINLASYKGKWVVLFFYPL...
A0A0M5IXP6,"[None, None, None, None, None, None, None, Non...",MNPSANESGVCSPVQIGDAAPNFQARTTLGEMSLSDYRGRWVLLFS...
...,...,...
U4UHL9,"[None, None, None, None, None, None, None, Non...",MANTNTDLTEEDAADLQFPKGITSNKLLCGNRFLNLLDSRPQLPTT...
A0A6J2XE68,"[None, None, None, None, None, None, None, Non...",MANVNTDLTEEDAADLQFPKDSTSQIPTTSTLVNVSDKNVILGYCS...
A0A834MIF3,"[None, None, None, None, None, None, None, Non...",MANVNTDLTEEDAADLQFPKDATSQKPSTSSVVNVSDKSIILGYCS...
A0A653BD21,"[None, None, None, None, None, None, None, Non...",MANTNTDLTEEDAADLQFPKADELAKTTLSYVSTNTFLDNPDSSYC...
D6WIZ3,"[None, None, None, None, None, PF25299.1, PF25...",DSDSVCSNCSCDLVAPYIYCALCKVNICSLCFSKGAEFGGHKNDHD...

In [4]:
# filter out sequences with more than 500 amino acids
dataset_df["seq_len"] = dataset_df["sequence"].apply(lambda x: len(x))
dataset_df = dataset_df[dataset_df["seq_len"] <= 500]
dataset_df

,pfam_tensor,sequence,seq_len
A1AL94,"[None, None, None, None, None, None, None, Non...",MSLTTLVTQQAPDFTAEAVMADNSFASITLSSLKGKFVLLLFYPLD...,198
A0A0F7V1V9,"[None, None, None, None, None, None, None, Non...",MAACLRAARLSLRQMEGLIEPSVRGRSSPLSMVRLLPSSSVSSSSP...,283
Q4UGC8,"[None, None, None, None, None, None, None, Non...",MKLTGISLISSLSYIRNTLPLKNTLTAFHTLNTRNNLKSVNRITSV...,261
A4H879,"[None, None, None, None, None, None, None, Non...",MSCGDAKMNEPAPPFEEMALMPNGSFKKINLASYKGKWVVLFFYPL...,199
A0A0M5IXP6,"[None, None, None, None, None, None, None, Non...",MNPSANESGVCSPVQIGDAAPNFQARTTLGEMSLSDYRGRWVLLFS...,221
...,...,...,...
A0A4U5NBC5,"[None, None, None, None, None, None, None, Non...",MTDSSPHLKRDEVVRQCCICISTLNGACIKCVECKRKTTFLCVPCF...,419
U4UHL9,"[None, None, None, None, None, None, None, Non...",MANTNTDLTEEDAADLQFPKGITSNKLLCGNRFLNLLDSRPQLPTT...,474
A0A6J2XE68,"[None, None, None, None, None, None, None, Non...",MANVNTDLTEEDAADLQFPKDSTSQIPTTSTLVNVSDKNVILGYCS...,460
A0A653BD21,"[None, None, None, None, None, None, None, Non...",MANTNTDLTEEDAADLQFPKADELAKTTLSYVSTNTFLDNPDSSYC...,462
D6WIZ3,"[None, None, None, None, None, PF25299.1, PF25...",DSDSVCSNCSCDLVAPYIYCALCKVNICSLCFSKGAEFGGHKNDHD...,419

In [5]:
subset_df = dataset_df.head(10000)
subset_df

,pfam_tensor,sequence,seq_len
A1AL94,"[None, None, None, None, None, None, None, Non...",MSLTTLVTQQAPDFTAEAVMADNSFASITLSSLKGKFVLLLFYPLD...,198
A0A0F7V1V9,"[None, None, None, None, None, None, None, Non...",MAACLRAARLSLRQMEGLIEPSVRGRSSPLSMVRLLPSSSVSSSSP...,283
Q4UGC8,"[None, None, None, None, None, None, None, Non...",MKLTGISLISSLSYIRNTLPLKNTLTAFHTLNTRNNLKSVNRITSV...,261
A4H879,"[None, None, None, None, None, None, None, Non...",MSCGDAKMNEPAPPFEEMALMPNGSFKKINLASYKGKWVVLFFYPL...,199
A0A0M5IXP6,"[None, None, None, None, None, None, None, Non...",MNPSANESGVCSPVQIGDAAPNFQARTTLGEMSLSDYRGRWVLLFS...,221
...,...,...,...
Q9A6W1,"[None, None, None, None, None, None, None, Non...",MAQAERPSASRLVAIATERHLIMKNPDSRRGRKDRRKEPRYQVKRR...,210
A9WHE0,"[PF03992.22, PF03992.22, PF03992.22, PF03992.2...",MYGLIGKMRATPGQRDALIAILVEGASSMPGCLSYVVAQDPKDPDA...,100
Q8Y824,"[None, None, None, PF03992.22, PF03992.22, PF0...",MKVGYGLLTAFYTHPGERDHLVKILLEAAESLEEYNTCIQYIVSES...,102
Q9ZBJ4,"[None, PF03992.22, PF03992.22, PF03992.22, PF0...",MTYGCIASMKTRPGFREEVVSLLLSAADGLRDAGCELYVVGLSEDD...,99
Q9RSM4,"[None, None, None, None, None, None, None, Non...",MSPQSMLTSPQHPRRTTMVISHGTLSASAEHAAHLRQLLVHIAQAT...,118

In [6]:
# Save sequences to fasta file
from Bio import SeqIO
from Bio.Seq import Seq

# create column if from index
subset_df["id"] = subset_df.index.astype(str)

with open("test_sequences.fasta", "w") as fasta_file:
    for index, row in subset_df.iterrows():
        seq = Seq(row["sequence"])
        record = SeqIO.SeqRecord(seq, id=row["id"], description="")
        SeqIO.write(record, fasta_file, "fasta")

/tmp/ipykernel_2992514/1764927560.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df["id"] = subset_df.index.astype(str)

In [ ]:
from Bio import SeqIO

fasta_path = "../../dataset/easy_subset_19k.fasta"  # update with your file path

headers = [record.id for record in SeqIO.parse(fasta_path, "fasta")]
print(headers)

FileNotFoundError: [Errno 2] No such file or directory: '../dataset/easy_subset_19k.fasta'

In [8]:
from model_parts import CUSTOM_ALPHABET
from model import MAX_PROTEIN_LENGTH

# one hot encode sequences and pad to max length
def one_hot_encode(sequence, alphabet=CUSTOM_ALPHABET, max_length=MAX_PROTEIN_LENGTH):
    one_hot = np.zeros((max_length, len(alphabet)), dtype=np.float32)
    for i, char in enumerate(sequence):
        # padding is done with tensor [1,0,0,...]
        if i < max_length and char in alphabet:
            one_hot[i, alphabet[char]] = 1.0
    
    return one_hot

# apply one hot encoding to sequences
subset_df["one_hot"] = subset_df["sequence"].apply(one_hot_encode)

subset_df

/tmp/ipykernel_391859/2064692852.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df["one_hot"] = subset_df["sequence"].apply(one_hot_encode)

,pfam_tensor,sequence,seq_len,one_hot
A1AL94,"[None, None, None, None, None, None, None, Non...",MSLTTLVTQQAPDFTAEAVMADNSFASITLSSLKGKFVLLLFYPLD...,198,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
A0A0F7V1V9,"[None, None, None, None, None, None, None, Non...",MAACLRAARLSLRQMEGLIEPSVRGRSSPLSMVRLLPSSSVSSSSP...,283,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
Q4UGC8,"[None, None, None, None, None, None, None, Non...",MKLTGISLISSLSYIRNTLPLKNTLTAFHTLNTRNNLKSVNRITSV...,261,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
A4H879,"[None, None, None, None, None, None, None, Non...",MSCGDAKMNEPAPPFEEMALMPNGSFKKINLASYKGKWVVLFFYPL...,199,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
A0A0M5IXP6,"[None, None, None, None, None, None, None, Non...",MNPSANESGVCSPVQIGDAAPNFQARTTLGEMSLSDYRGRWVLLFS...,221,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
...,...,...,...,...
Q9A6W1,"[None, None, None, None, None, None, None, Non...",MAQAERPSASRLVAIATERHLIMKNPDSRRGRKDRRKEPRYQVKRR...,210,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
A9WHE0,"[PF03992.22, PF03992.22, PF03992.22, PF03992.2...",MYGLIGKMRATPGQRDALIAILVEGASSMPGCLSYVVAQDPKDPDA...,100,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
Q8Y824,"[None, None, None, PF03992.22, PF03992.22, PF0...",MKVGYGLLTAFYTHPGERDHLVKILLEAAESLEEYNTCIQYIVSES...,102,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
Q9ZBJ4,"[None, PF03992.22, PF03992.22, PF03992.22, PF0...",MTYGCIASMKTRPGFREEVVSLLLSAADGLRDAGCELYVVGLSEDD...,99,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
Q9RSM4,"[None, None, None, None, None, None, None, Non...",MSPQSMLTSPQHPRRTTMVISHGTLSASAEHAAHLRQLLVHIAQAT...,118,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."

In [20]:
len(subset_df["pfam_tensor"].explode().unique())


pfam_to_index = {pfam: idx+1 for idx, pfam in enumerate(subset_df["pfam_tensor"].explode().unique())}

pfam_to_index

{None: 1,
 'PF10417.14': 2,
 'PF00578.27': 3,
 'PF21734.3': 4,
 'PF09847.15': 5,
 'PF00244.26': 6,
 'PF16998.10': 7,
 'PF00389.36': 8,
 'PF02826.25': 9,
 'PF02817.22': 10,
 'PF00198.28': 11,
 'PF00364.28': 12,
 'PF16078.10': 13,
 'PF04029.19': 14,
 'PF04463.17': 15,
 'PF13302.13': 16,
 'PF01288.25': 17,
 'PF08349.16': 18,
 'PF05635.17': 19,
 'PF22546.2': 20,
 'PF22545.2': 21,
 'PF08521.16': 22,
 'PF08793.15': 23,
 'PF20150.5': 24,
 'PF11591.13': 25,
 'PF01257.25': 26,
 'PF08975.16': 27,
 'PF22547.2': 28,
 'PF03390.20': 29,
 'PF21584.2': 30,
 'PF03171.26': 31,
 'PF14226.12': 32,
 'PF10637.15': 33,
 'PF13532.12': 34,
 'PF13640.12': 35,
 'PF08336.16': 36,
 'PF18331.6': 37,
 'PF13661.12': 38,
 'PF13759.12': 39,
 'PF20515.4': 40,
 'PF10014.15': 41,
 'PF13239.11': 42,
 'PF06580.19': 43,
 'PF23143.1': 44,
 'PF13563.12': 45,
 'PF06983.19': 46,
 'PF06052.18': 47,
 'PF01073.25': 48,
 'PF14934.11': 49,
 'PF06725.17': 50,
 'PF03562.22': 51,
 'PF03990.20': 52,
 'PF07501.17': 53,
 'PF01471.23': 54,
 'PF02829.19': 55,
 'PF08279.18': 56,
 'PF13238.12': 57,
 'PF07885.22': 58,
 'PF02254.24': 59,
 'PF22951.1': 60,
 'PF02737.24': 61,
 'PF00725.27': 62,
 'PF18321.7': 63,
 'PF06439.18': 64,
 'PF16121.10': 65,
 'PF00900.26': 66,
 'PF08071.17': 67,
 'PF01479.30': 68,
 'PF00467.35': 69,
 'PF16122.10': 70,
 'PF03061.28': 71,
 'PF13279.12': 72,
 'PF13622.12': 73,
 'PF20789.3': 74,
 'PF23313.1': 75,
 'PF12729.13': 76,
 'PF04476.19': 77,
 'PF02152.23': 78,
 'PF18671.6': 79,
 'PF18524.6': 80,
 'PF17837.6': 81,
 'PF05902.18': 82,
 'PF01812.26': 83,
 'PF06189.17': 84,
 'PF21432.3': 85,
 'PF03491.18': 86,
 'PF07694.17': 87,
 'PF25221.1': 88,
 'PF02739.22': 89,
 'PF01367.25': 90,
 'PF05761.20': 91,
 'PF02872.23': 92,
 'PF02096.25': 93,
 'PF01591.24': 94,
 'PF00393.24': 95,
 'PF03446.21': 96,
 'PF22242.1': 97,
 'PF23022.3': 98,
 'PF23021.3': 99,
 'PF07698.17': 100,
 'PF07696.17': 101,
 'PF07695.17': 102,
 'PF00001.26': 103,
 'PF00002.29': 104,
 'PF00003.28': 105,
 'PF07562.20': 106,
 'PF13853.12': 107,
 'PF02949.25': 108,
 'PF08395.17': 109,
 'PF02117.22': 110,
 'PF10292.15': 111,
 'PF02175.22': 112,
 'PF10316.15': 113,
 'PF10317.15': 114,
 'PF10318.15': 115,
 'PF10327.15': 116,
 'PF10319.15': 117,
 'PF10320.15': 118,
 'PF10321.15': 119,
 'PF10322.15': 120,
 'PF10323.15': 121,
 'PF10324.15': 122,
 'PF10328.15': 123,
 'PF10325.15': 124,
 'PF10326.15': 125,
 'PF14400.11': 126,
 'PF14402.11': 127,
 'PF17028.10': 128,
 'PF24838.2': 129,
 'PF24792.1': 130,
 'PF07388.17': 131,
 'PF07966.17': 132,
 'PF06750.18': 133,
 'PF01478.23': 134,
 'PF08792.16': 135,
 'PF04947.19': 136,
 'PF00207.28': 137,
 'PF07703.20': 138,
 'PF07677.20': 139,
 'PF21631.3': 140,
 'PF13840.12': 141,
 'PF03443.20': 142,
 'PF00734.23': 143,
 'PF07142.17': 144,
 'PF00004.35': 145,
 'PF23900.1': 146,
 'PF17862.7': 147,
 'PF09820.16': 148,
 'PF13087.12': 149,
 'PF13173.12': 150,
 'PF13635.12': 151,
 'PF13175.12': 152,
 'PF13191.12': 153,
 'PF21639.3': 154,
 'PF14630.12': 155,
 'PF13207.12': 156,
 'PF01877.22': 157,
 'PF00156.33': 158,
 'PF13245.12': 159,
 'PF07724.20': 160,
 'PF13304.12': 161,
 'PF12476.13': 162,
 'PF13401.12': 163,
 'PF13476.12': 164,
 'PF13479.12': 165,
 'PF13481.12': 166,
 'PF13500.12': 167,
 'PF13649.12': 168,
 'PF13521.12': 169,
 'PF13555.12': 170,
 'PF07726.17': 171,
 'PF17863.7': 172,
 'PF13604.12': 173,
 'PF13614.12': 174,
 'PF13671.12': 175,
 'PF01966.28': 176,
 'PF13872.12': 177,
 'PF14516.12': 178,
 'PF07728.20': 179,
 'PF20265.3': 180,
 'PF12592.13': 181,
 'PF12775.13': 182,
 'PF14363.11': 183,
 'PF16193.11': 184,
 'PF12002.13': 185,
 'PF09821.14': 186,
 'PF21396.3': 187,
 'PF22227.1': 188,
 'PF23232.1': 189,
 'PF21964.2': 190,
 'PF06480.20': 191,
 'PF09336.16': 192,
 'PF16450.11': 193,
 'PF05496.18': 194,
 'PF17864.7': 195,
 'PF17866.7': 196,
 'PF17868.7': 197,
 'PF17871.7': 198,
 'PF25426.1': 199,
 'PF08740.16': 200,
 'PF25408.1': 201,
 'PF23902.1': 202,
 'PF25361.1': 203,
 'PF23242.1': 204,
 'PF23563.1': 205,
 'PF13427.11': 206,
 'PF01909.29': 207,
 'PF03306.18': 208,
 'PF20981.2': 209,
 'PF05282.17': 210,
 'PF08142.18': 211,
 'PF22624.1': 212,
 'PF03417.21': 213,
 'PF07247.17': 214,
 'PF13339.11': 215,
 'PF08164.17': 216,
 'PF00696.33': 217,
 'PF22468.2': 218,
 'PF00324.27': 219,
 'PF13520.12': 220,
 'PF13906.12': 221,
 'PF06684.16': 222,
 'PF01490.24': 223,
 'PF14108.11': 224,
 'PF07336.16': 225,
 'PF11706.13': 226,
 'PF12430.13': 227,
 'PF12537.13': 228,
 'PF02496.21': 229,
 'PF14156.11': 230,
 'PF00950.22': 231,
 'PF03109.22': 232,
 'PF01061.29': 233,
 'PF12679.13': 234,
 'PF12698.13': 235,
 'PF12730.13': 236,
 'PF13346.12': 237,
 'PF06182.17': 238,
 'PF25158.1': 239,
 'PF24526.1': 240,
 'PF24358.1': 241,
 'PF21707.3': 242,
 'PF20446.3': 243,
 'PF09818.15': 244,
 'PF21709.3': 245,
 'PF09819.14': 246,
 'PF13748.11': 247,
 'PF04392.18': 248,
 'PF00005.33': 249,
 'PF09822.16': 250,
 'PF23357.1': 251,
 'PF03886.18': 252,
 'PF06541.16': 253,
 'PF14510.11': 254,
 'PF16326.10': 255,
 'PF12407.13': 256,
 'PF05270.19': 257,
 'PF09206.18': 258,
 'PF18225.7': 259,
 'PF22990.1': 260,
 'PF09752.15': 261,
 'PF22316.2': 262,
 'PF00561.26': 263,
 'PF20091.5': 264,
 'PF20408.4': 265,
 'PF02230.22': 266,
 'PF07859.19': 267,
 'PF08386.16': 268,
 'PF12695.13': 269,
 'PF12697.13': 270,
 'PF00708.24': 271,
 'PF12715.13': 272,
 'PF06259.18': 273,
 'PF10081.15': 274,
 'PF15420.11': 275,
 'PF04083.22': 276,
 'PF08843.17': 277,
 'PF13338.12': 278,
 'PF09407.15': 279,
 'PF09952.14': 280,
 'PF17194.10': 281,
 'PF11459.13': 282,
 'PF10899.13': 283,
 'PF16873.10': 284,
 'PF14253.11': 285,
 'PF18860.6': 286,
 'PF14355.11': 287,
 'PF18863.6': 288,
 'PF18865.6': 289,
 'PF18864.6': 290,
 'PF07751.16': 291,
 'PF14337.12': 292,
 'PF07815.19': 293,
 'PF16182.10': 294,
 'PF02209.24': 295,
 'PF03992.22': 296}

In [9]:
# get unique pfam_ids
unique_pfams = set()

for pfam_list in subset_df["pfam_tensor"]:
    for pfam in pfam_list:
        unique_pfams.add(pfam)

# create a mapping from pfam_id to index
pfam_to_index = {pfam: i for i, pfam in enumerate(unique_pfams)}

# one hot encode pfam tensors and pad to max length
def pad_pfam_tensor(pfam_tensor, max_length=MAX_PROTEIN_LENGTH):
    padded_tensor = np.zeros((max_length,len(pfam_to_index)), dtype=np.float32)
    for i, pfam in enumerate(pfam_tensor):
        if i < max_length:
            padded_tensor[i, pfam_to_index.get(pfam, 0)] = 1.0  # use 0 for unknown pfams
    return padded_tensor

# apply one hot encoding to pfam tensors
subset_df["pfam_one_hot"] = subset_df["pfam_tensor"].apply(pad_pfam_tensor)

subset_df

/tmp/ipykernel_391859/2085954855.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df["pfam_one_hot"] = subset_df["pfam_tensor"].apply(pad_pfam_tensor)

,pfam_tensor,sequence,seq_len,one_hot,pfam_one_hot
A1AL94,"[None, None, None, None, None, None, None, Non...",MSLTTLVTQQAPDFTAEAVMADNSFASITLSSLKGKFVLLLFYPLD...,198,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
A0A0F7V1V9,"[None, None, None, None, None, None, None, Non...",MAACLRAARLSLRQMEGLIEPSVRGRSSPLSMVRLLPSSSVSSSSP...,283,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
Q4UGC8,"[None, None, None, None, None, None, None, Non...",MKLTGISLISSLSYIRNTLPLKNTLTAFHTLNTRNNLKSVNRITSV...,261,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
A4H879,"[None, None, None, None, None, None, None, Non...",MSCGDAKMNEPAPPFEEMALMPNGSFKKINLASYKGKWVVLFFYPL...,199,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
A0A0M5IXP6,"[None, None, None, None, None, None, None, Non...",MNPSANESGVCSPVQIGDAAPNFQARTTLGEMSLSDYRGRWVLLFS...,221,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
...,...,...,...,...,...
Q9A6W1,"[None, None, None, None, None, None, None, Non...",MAQAERPSASRLVAIATERHLIMKNPDSRRGRKDRRKEPRYQVKRR...,210,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
A9WHE0,"[PF03992.22, PF03992.22, PF03992.22, PF03992.2...",MYGLIGKMRATPGQRDALIAILVEGASSMPGCLSYVVAQDPKDPDA...,100,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
Q8Y824,"[None, None, None, PF03992.22, PF03992.22, PF0...",MKVGYGLLTAFYTHPGERDHLVKILLEAAESLEEYNTCIQYIVSES...,102,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
Q9ZBJ4,"[None, PF03992.22, PF03992.22, PF03992.22, PF0...",MTYGCIASMKTRPGFREEVVSLLLSAADGLRDAGCELYVVGLSEDD...,99,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
Q9RSM4,"[None, None, None, None, None, None, None, Non...",MSPQSMLTSPQHPRRTTMVISHGTLSASAEHAAHLRQLLVHIAQAT...,118,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."

In [17]:
pfam_to_index

{'PF06615.16': 0,
 'PF08796.15': 1,
 'PF10439.15': 2,
 'PF16121.10': 3,
 'PF06698.16': 4,
 'PF06620.16': 5,
 'PF07043.18': 6,
 'PF00779.24': 7,
 'PF16860.10': 8,
 'PF12966.13': 9,
 'PF07125.16': 10,
 'PF16689.10': 11,
 'PF08991.16': 12,
 'PF15355.11': 13,
 'PF00313.28': 14,
 'PF05627.16': 15,
 'PF09713.15': 16,
 'PF02627.25': 17,
 'PF08742.16': 18,
 'PF08979.16': 19,
 'PF22586.1': 20,
 'PF12121.13': 21,
 'PF00895.25': 22,
 'PF07076.17': 23,
 'PF08026.16': 24,
 'PF07210.18': 25,
 'PF08846.15': 26,
 'PF17866.7': 27,
 'PF02805.21': 28,
 'PF01313.24': 29,
 'PF21825.2': 30,
 'PF20829.2': 31,
 'PF12133.13': 32,
 'PF04940.18': 33,
 'PF18277.6': 34,
 'PF05293.16': 35,
 'PF00228.25': 36,
 'PF15116.11': 37,
 'PF06568.16': 38,
 'PF03777.18': 39,
 'PF09048.16': 40,
 'PF07369.16': 41,
 'PF04691.17': 42,
 'PF05968.16': 43,
 'PF13318.11': 44,
 'PF22754.3': 45,
 'PF06639.16': 46,
 'PF09082.15': 47,
 'PF09707.15': 48,
 'PF10438.15': 49,
 'PF03992.22': 50,
 'PF20520.3': 51,
 'PF17793.6': 52,
 'PF08109.16': 53,
 'PF08107.16': 54,
 'PF02823.21': 55,
 'PF13233.12': 56,
 'PF21023.2': 57,
 'PF14159.11': 58,
 'PF04711.18': 59,
 'PF00385.30': 60,
 'PF07716.20': 61,
 'PF00137.26': 62,
 'PF16981.10': 63,
 'PF00936.24': 64,
 'PF21102.3': 65,
 'PF21975.1': 66,
 'PF21617.2': 67,
 'PF01817.26': 68,
 'PF05864.17': 69,
 'PF20274.4': 70,
 'PF05899.18': 71,
 'PF02234.24': 72,
 'PF08899.16': 73,
 'PF25111.1': 74,
 'PF05186.18': 75,
 'PF06773.16': 76,
 'PF14420.11': 77,
 'PF01721.23': 78,
 'PF18593.6': 79,
 'PF00323.24': 80,
 'PF07659.16': 81,
 'PF10172.14': 82,
 'PF15321.11': 83,
 'PF09600.15': 84,
 'PF21862.1': 85,
 'PF01985.26': 86,
 'PF06688.16': 87,
 'PF01990.22': 88,
 'PF22282.1': 89,
 'PF24654.2': 90,
 'PF12716.12': 91,
 'PF05803.17': 92,
 'PF24238.1': 93,
 'PF06015.17': 94,
 'PF14657.12': 95,
 'PF15104.11': 96,
 'PF05258.17': 97,
 'PF06096.16': 98,
 'PF00452.24': 99,
 'PF04952.20': 100,
 'PF10719.14': 101,
 'PF07311.17': 102,
 'PF08018.16': 103,
 'PF06900.16': 104,
 'PF05846.17': 105,
 'PF08181.16': 106,
 'PF01320.23': 107,
 'PF13356.12': 108,
 'PF08922.17': 109,
 'PF20271.3': 110,
 'PF21784.3': 111,
 'PF02944.25': 112,
 'PF06269.17': 113,
 'PF07599.16': 114,
 'PF07841.18': 115,
 'PF12515.13': 116,
 'PF11057.13': 117,
 'PF14862.11': 118,
 'PF11604.15': 119,
 'PF06442.17': 120,
 'PF07866.17': 121,
 'PF06882.17': 122,
 'PF08112.16': 123,
 'PF18671.6': 124,
 'PF02822.19': 125,
 'PF02791.22': 126,
 'PF08827.16': 127,
 'PF14556.11': 128,
 'PF07362.18': 129,
 'PF10346.14': 130,
 'PF07308.18': 131,
 'PF12190.13': 132,
 'PF00031.27': 133,
 'PF09489.15': 134,
 'PF04110.19': 135,
 'PF08895.16': 136,
 'PF02085.21': 137,
 'PF22372.1': 138,
 'PF09236.15': 139,
 'PF22166.2': 140,
 'PF02043.22': 141,
 'PF18425.6': 142,
 'PF05493.18': 143,
 'PF06643.16': 144,
 'PF02560.19': 145,
 'PF00708.24': 146,
 'PF07027.17': 147,
 'PF18909.5': 148,
 'PF05814.16': 149,
 'PF15243.11': 150,
 'PF00879.23': 151,
 'PF06725.17': 152,
 'PF06440.16': 153,
 'PF04739.20': 154,
 'PF08945.15': 155,
 'PF06203.19': 156,
 'PF15360.11': 157,
 'PF05778.17': 158,
 'PF07411.17': 159,
 'PF14705.12': 160,
 'PF06270.16': 161,
 'PF05392.16': 162,
 'PF08201.16': 163,
 'PF16020.10': 164,
 'PF04266.20': 165,
 'PF03047.20': 166,
 'PF10515.14': 167,
 'PF10729.15': 168,
 'PF14206.11': 169,
 'PF02937.20': 170,
 'PF08285.16': 171,
 'PF07441.16': 172,
 'PF01037.27': 173,
 'PF09010.15': 174,
 'PF01302.31': 175,
 'PF10471.14': 176,
 'PF05528.17': 177,
 'PF18249.6': 178,
 'PF04021.17': 179,
 'PF17557.7': 180,
 'PF04623.17': 181,
 'PF07206.16': 182,
 'PF07038.16': 183,
 'PF03477.21': 184,
 'PF01842.31': 185,
 'PF01393.25': 186,
 'PF15270.11': 187,
 'PF05961.16': 188,
 'PF02740.20': 189,
 'PF06531.16': 190,
 'PF06397.17': 191,
 'PF02044.22': 192,
 'PF06231.16': 193,
 'PF00200.28': 194,
 'PF24673.1': 195,
 'PF07621.16': 196,
 'PF09221.15': 197,
 'PF02519.19': 198,
 'PF10781.14': 199,
 'PF17223.8': 200,
 'PF06713.17': 201,
 'PF02723.19': 202,
 'PF04972.22': 203,
 'PF15013.11': 204,
 'PF08338.16': 205,
 'PF11123.14': 206,
 'PF00473.22': 207,
 'PF21368.3': 208,
 'PF12032.13': 209,
 'PF17696.6': 210,
 'PF14777.11': 211,
 'PF04718.20': 212,
 'PF06592.18': 213,
 'PF02594.21': 214,
 'PF18775.7': 215,
 'PF00649.23': 216,
 'PF08958.15': 217,
 'PF07896.17': 218,
 'PF25361.1': 219,
 'PF18973.5': 220,
 'PF06569.16': 221,
 'PF07484.17': 222,
 'PF09204.15': 223,
 'PF10945.13': 224,
 'PF06747.18': 225,
 'PF02935.21': 226,
 'PF08947.15': 227,
 'PF07436.16': 228,
 'PF08077.16': 229,
 'PF17500.7': 230,
 'PF06633.16': 231,
 'PF07835.17': 232,
 'PF05790.21': 233,
 'PF00283.24': 234,
 'PF06523.16': 235,
 'PF22147.1': 236,
 'PF07045.17': 237,
 'PF02839.19': 238,
 'PF07330.17': 239,
 'PF09501.15': 240,
 'PF08980.16': 241,
 'PF09399.15': 242,
 'PF16760.10': 243,
 'PF14591.11': 244,
 'PF25164.1': 245,
 'PF17860.6': 246,
 'PF05437.17': 247,
 'PF03123.20': 248,
 'PF01383.26': 249,
 'PF00711.24': 250,
 'PF04380.18': 251,
 'PF06781.17': 252,
 'PF04365.19': 253,
 'PF07361.16': 254,
 'PF13508.13': 255,
 'PF02863.23': 256,
 'PF05051.18': 257,
 'PF15188.11': 258,
 'PF18721.6': 259,
 'PF24205.1': 260,
 'PF08346.17': 261,
 'PF03692.20': 262,
 'PF08104.16': 263,
 'PF07877.16': 264,
 'PF08410.15': 265,
 'PF16594.10': 266,
 'PF14743.12': 267,
 'PF07853.16': 268,
 'PF11402.13': 269,
 'PF07119.17': 270,
 'PF07205.16': 271,
 'PF06336.17': 272,
 'PF07193.17': 273,
 'PF01998.22': 274,
 'PF16484.10': 275,
 'PF01693.22': 276,
 'PF07408.16': 277,
 'PF12662.13': 278,
 'PF08986.15': 279,
 'PF06515.16': 280,
 'PF11525.13': 281,
 'PF20712.2': 282,
 'PF13710.12': 283,
 'PF08113.16': 284,
 'PF11773.13': 285,
 'PF02238.20': 286,
 'PF12652.12': 287,
 'PF05372.16': 288,
 'PF08649.15': 289,
 'PF07048.16': 290,
 'PF02845.22': 291,
 'PF14375.11': 292,
 'PF12924.12': 293,
 'PF09649.15': 294,
 'PF08230.16': 295,
 'PF07208.16': 296,
 'PF02496.21': 297,
 'PF07347.17': 298,
 'PF07358.16': 299,
 'PF00187.25': 300,
 'PF04627.18': 301,
 'PF08956.15': 302,
 'PF20605.4': 303,
 'PF03091.20': 304,
 'PF11520.13': 305,
 'PF23526.1': 306,
 'PF02641.20': 307,
 'PF07256.17': 308,
 'PF21716.3': 309,
 'PF07459.16': 310,
 'PF02599.21': 311,
 'PF21627.2': 312,
 'PF07371.17': 313,
 None: 314,
 'PF06961.18': 315,
 'PF09527.15': 316,
 'PF15198.11': 317,
 'PF12173.13': 318,
 'PF07151.18': 319,
 'PF08860.15': 320,
 'PF06183.18': 321,
 'PF01388.27': 322,
 'PF00216.26': 323,
 'PF05358.17': 324,
 'PF06857.16': 325,
 'PF20814.2': 326,
 'PF09620.15': 327,
 'PF14860.11': 328,
 'PF20068.4': 329,
 'PF00272.24': 330,
 'PF18084.6': 331,
 'PF14406.12': 332,
 'PF02950.22': 333,
 'PF14207.11': 334,
 'PF00166.26': 335,
 'PF07131.17': 336,
 'PF02398.22': 337,
 'PF06649.17': 338,
 'PF05532.17': 339,
 'PF07883.17': 340,
 'PF11758.13': 341,
 'PF07677.20': 342,
 'PF07875.18': 343,
 'PF14138.11': 344,
 'PF23544.1': 345,
 'PF07966.17': 346,
 'PF09827.14': 347,
 'PF06803.17': 348,
 'PF01111.24': 349,
 'PF07533.21': 350,
 'PF16366.10': 351,
 'PF07876.18': 352,
 'PF06341.16': 353,
 'PF07384.17': 354,
 'PF11395.13': 355,
 'PF11731.14': 356,
 'PF06145.16': 357,
 'PF22184.2': 358,
 'PF15630.12': 359,
 'PF05952.17': 360,
 'PF08656.15': 361,
 'PF06726.17': 362,
 'PF08044.16': 363,
 'PF13442.11': 364,
 'PF01104.22': 365,
 'PF08672.17': 366,
 'PF08194.17': 367,
 'PF14255.11': 368,
 'PF07282.18': 369,
 'PF10775.14': 370,
 'PF00734.23': 371,
 'PF13817.11': 372,
 'PF06522.17': 373,
 'PF09413.15': 374,
 'PF22581.1': 375,
 'PF21671.2': 376,
 'PF05730.16': 377,
 'PF17000.10': 378,
 'PF06611.17': 379,
 'PF06842.17': 380,
 'PF07023.17': 381,
 'PF02977.21': 382,
 'PF14300.12': 383,
 'PF10133.14': 384,
 'PF21221.3': 385,
 'PF08031.17': 386,
 'PF05829.17': 387,
 'PF09227.15': 388,
 'PF25095.1': 389,
 'PF07618.16': 390,
 'PF00887.24': 391,
 'PF01337.24': 392,
 'PF18789.6': 393,
 'PF24729.2': 394,
 'PF00284.25': 395,
 'PF18524.6': 396,
 'PF08213.16': 397,
 'PF07129.17': 398,
 'PF08940.17': 399,
 'PF20077.4': 400,
 'PF07116.16': 401,
 'PF15674.10': 402,
 'PF06806.18': 403,
 'PF01722.23': 404,
 'PF00401.25': 405,
 'PF22034.2': 406,
 'PF07235.16': 407,
 'PF17050.10': 408,
 'PF05839.16': 409,
 'PF07297.17': 410,
 'PF03784.18': 411,
 'PF05160.18': 412,
 'PF01845.23': 413,
 'PF03861.19': 414,
 'PF05347.21': 415,
 'PF00034.26': 416,
 'PF06260.17': 417,
 'PF17862.7': 418,
 'PF04505.17': 419,
 'PF02045.20': 420,
 'PF00173.33': 421,
 'PF22489.1': 422,
 'PF24552.1': 423,
 'PF18512.6': 424,
 'PF08930.15': 425,
 'PF13857.12': 426,
 'PF08650.15': 427,
 'PF02017.21': 428,
 'PF16699.10': 429,
 'PF06380.16': 430,
 'PF02297.22': 431,
 'PF13822.11': 432,
 'PF03607.23': 433,
 'PF13991.11': 434,
 'PF12459.13': 435,
 'PF08129.17': 436,
 'PF14384.12': 437,
 'PF14984.11': 438,
 'PF10890.13': 439,
 'PF11410.13': 440,
 'PF13239.11': 441,
 'PF01918.26': 442,
 'PF08130.16': 443,
 'PF04942.19': 444,
 'PF14156.11': 445,
 'PF25449.1': 446,
 'PF08583.15': 447,
 'PF01954.22': 448,
 'PF17524.7': 449,
 'PF10557.15': 450,
 'PF08865.16': 451,
 'PF04714.18': 452,
 'PF01484.22': 453,
 'PF06275.16': 454,
 'PF03889.18': 455,
 'PF07203.16': 456,
 'PF07032.16': 457,
 'PF25052.1': 458,
 'PF09415.16': 459,
 'PF09000.15': 460,
 'PF15228.11': 461,
 'PF06906.16': 462,
 'PF08679.17': 463,
 'PF14408.11': 464,
 'PF11092.13': 465,
 'PF08972.17': 466,
 'PF22996.2': 467,
 'PF07351.18': 468,
 'PF07870.16': 469,
 'PF08098.16': 470,
 'PF09652.15': 471,
 'PF07280.16': 472,
 'PF22554.1': 473,
 'PF10868.14': 474,
 'PF07346.16': 475,
 'PF07561.16': 476,
 'PF14522.11': 477,
 'PF00379.29': 478,
 'PF00404.24': 479,
 'PF07312.16': 480,
 'PF04977.20': 481,
 'PF15170.11': 482,
 'PF11022.13': 483,
 'PF02285.20': 484,
 'PF21492.2': 485,
 'PF15335.11': 486,
 'PF07190.16': 487,
 'PF06392.17': 488,
 'PF08140.16': 489,
 'PF08953.17': 490,
 'PF07868.16': 491,
 'PF07874.16': 492,
 'PF10766.14': 493,
 'PF03626.19': 494,
 'PF06143.16': 495,
 'PF06949.16': 496,
 'PF02617.22': 497,
 'PF08180.16': 498,
 'PF00808.29': 499,
 'PF07142.17': 500,
 'PF14194.11': 501,
 'PF23792.1': 502,
 'PF08590.15': 503,
 'PF24769.1': 504,
 'PF02553.20': 505,
 'PF16048.10': 506,
 'PF14542.12': 507,
 'PF00619.27': 508,
 'PF12441.14': 509,
 'PF12095.13': 510,
 'PF17635.7': 511,
 'PF03513.19': 512,
 'PF13841.11': 513,
 'PF07864.16': 514,
 'PF09813.14': 515,
 'PF09076.15': 516,
 'PF07863.16': 517,
 'PF24570.1': 518,
 'PF14205.11': 519,
 'PF13270.11': 520,
 'PF04077.17': 521,
 'PF03669.18': 522,
 'PF05931.16': 523,
 'PF21801.3': 524,
 'PF06945.18': 525,
 'PF12407.13': 526,
 'PF16047.10': 527,
 'PF14960.11': 528,
 'PF06377.16': 529,
 'PF13586.12': 530,
 'PF07438.16': 531,
 'PF06612.16': 532,
 'PF08036.16': 533,
 'PF07293.16': 534,
 'PF08838.16': 535,
 'PF11512.13': 536,
 'PF17858.6': 537,
 'PF06706.16': 538,
 'PF21151.2': 539,
 'PF09313.17': 540,
 'PF07869.17': 541,
 'PF12265.14': 542,
 'PF14880.11': 543,
 'PF15510.12': 544,
 'PF22926.2': 545,
 'PF08809.16': 546,
 'PF12106.13': 547,
 'PF12655.13': 548,
 'PF10470.14': 549,
 'PF01473.26': 550,
 'PF08134.16': 551,
 'PF17366.7': 552,
 'PF06526.17': 553,
 'PF17333.7': 554,
 'PF15777.11': 555,
 'PF02038.21': 556,
 'PF25048.1': 557,
 'PF20543.3': 558,
 'PF08898.15': 559,
 'PF10796.14': 560,
 'PF06373.16': 561,
 'PF04538.17': 562,
 'PF06288.18': 563,
 'PF07911.18': 564,
 'PF07797.19': 565,
 'PF06348.16': 566,
 'PF05710.17': 567,
 'PF18152.6': 568,
 'PF16839.10': 569,
 'PF23493.1': 570,
 'PF22995.2': 571,
 'PF07383.17': 572,
 'PF08132.16': 573,
 'PF22629.2': 574,
 'PF05680.17': 575,
 'PF06493.16': 576,
 'PF06712.16': 577,
 'PF01623.22': 578,
 'PF06627.17': 579,
 'PF08227.16': 580,
 'PF07872.16': 581,
 'PF11007.13': 582,
 'PF11347.14': 583,
 'PF08990.16': 584,
 'PF07097.16': 585,
 'PF07865.16': 586,
 'PF09350.15': 587,
 'PF04995.19': 588,
 'PF04911.17': 589,
 'PF10161.14': 590,
 'PF06376.17': 591,
 'PF21432.3': 592,
 'PF14250.11': 593,
 'PF00751.23': 594,
 'PF03905.18': 595,
 'PF07026.16': 596,
 'PF07342.17': 597,
 'PF07867.16': 598,
 'PF07214.17': 599,
 'PF01035.26': 600,
 'PF00778.23': 601,
 'PF08105.16': 602,
 'PF12734.12': 603,
 'PF10235.14': 604,
 'PF08984.16': 605,
 'PF23491.1': 606,
 'PF06844.16': 607,
 'PF11839.13': 608,
 'PF20821.2': 609,
 'PF10197.14': 610,
 'PF07785.16': 611,
 'PF10815.13': 612,
 'PF24926.1': 613,
 'PF06287.16': 614,
 'PF22323.1': 615,
 'PF02180.22': 616,
 'PF21188.2': 617,
 'PF14916.11': 618,
 'PF16996.10': 619,
 'PF06150.17': 620,
 'PF08766.16': 621,
 'PF06563.17': 622,
 'PF17334.7': 623,
 'PF20824.2': 624,
 'PF11120.13': 625,
 'PF23626.1': 626,
 'PF02672.20': 627}

In [61]:
subset_df

,pfam_tensor,sequence,seq_len,one_hot,pfam_one_hot
G2Z1S9,"[None, None, None, None, None, None, None, Non...",MENYNQIDERYIAAQKRVQEIKGFYGHLASYVLVNLFLLILNLVSS...,96,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
A4CNS3,"[None, None, None, None, None, None, None, Non...",MEDFKKESKYIRARERVEELKKFYGNVASYIFVITLLGIINYLTYW...,100,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
G0L8V4,"[None, None, None, None, None, None, None, PF1...",MERESKYIRAKERVEREKKFYNGLISYVVTISFLAAINYYTNGFAY...,97,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
A4CNS4,"[None, None, None, None, None, None, None, Non...",MEDFSHADRYLRAKKRVEDIRGFYGNLITYLIVIPFLIWLNWRTTS...,93,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
F9YQQ0,"[None, None, None, None, None, None, None, Non...",MNTIEPNAYRKAEKRVKKLKKFYHHLATYVVVNTFLVGLNLYQTPN...,93,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
...,...,...,...,...,...
Q1GQN9,"[None, None, PF09413.15, PF09413.15, PF09413.1...",MPLVELVRLPNGAEAELLRGRLESAGVHAVCFDAGMNIAESVGLMI...,70,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
F8KZY9,"[None, None, None, PF09413.15, PF09413.15, PF0...",MNNFVCIYRTFDIVQANLIKSHFENEDILCVLKSNDASGILPHLGF...,74,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
A8F8N0,"[None, PF09413.15, PF09413.15, PF09413.15, PF0...",MWRILLEEVDLPTANILKSLLEESGIEVLIKPGSFDPVIFGQGGLV...,74,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
Q8A1E5,"[None, None, None, None, None, None, None, PF0...",MKEEDYSKAIEVFSGSPWEAEIIKGLLESNDIRCVIKDGIMGTLAP...,77,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
Q9WY53,"[None, None, PF09413.15, PF09413.15, PF09413.1...",MKWKTLIEGSELEVKMIEDILKENGVPYVVETCDDVTPRAIFGSSA...,69,"[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."

In [83]:
example_input = torch.tensor(np.stack(subset_df["one_hot"].values[:64]), dtype=torch.float32)

model = ProtENN2_style(num_pfams=len(pfam_to_index))

# example_input.shape

model(example_input).shape

torch.Size([64, 100, 628])

In [84]:
example_output = torch.tensor(np.stack(subset_df["pfam_one_hot"].values[:64]), dtype=torch.float32)

example_output.shape

torch.Size([64, 100, 628])

In [12]:
Y_onehot = np.stack(subset_df["pfam_one_hot"].values[:5000])  # (batch, 100, num_pfams)

Y = torch.tensor(Y_onehot.argmax(axis=-1), dtype=torch.long)

Y

tensor([[ 19,  19,  19,  ...,  19,  19,  19],
        [ 19,  19,  19,  ...,   4,   4,   4],
        [ 19,  19,  19,  ...,   4,   4,   4],
        ...,
        [ 19,  19,  19,  ..., 248, 248, 248],
        [ 19,  19,  19,  ..., 248, 248, 248],
        [ 19,  19,  19,  ..., 248, 248, 248]])

In [ ]:
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

# Prepare data
X = torch.tensor(np.stack(subset_df["one_hot"].values[:5000]), dtype=torch.float32)  # (batch, 100, 21)
Y_onehot = np.stack(subset_df["pfam_one_hot"].values[:5000])  # (batch, 100, num_pfams)
Y = torch.tensor(Y_onehot.argmax(axis=-1), dtype=torch.long)  # (batch, 100)

dataset = TensorDataset(X, Y)
loader = DataLoader(dataset, batch_size=250, shuffle=True)

model = ProtENN2_style(num_pfams=Y_onehot.shape[-1])
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
criterion = nn.CrossEntropyLoss()  # expects (N, C) and (N,) or (N, d1, d2, ...) and (N, d1, d2, ...)

# Training loop
for epoch in range(40):
    model.train()
    total_loss = 0
    for xb, yb in loader:
        optimizer.zero_grad()
        out = model(xb)  # (batch, 100, num_pfams)
        loss = criterion(out.view(-1, out.shape[-1]), yb.view(-1))  # flatten for CrossEntropyLoss
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch+1}, Loss: {total_loss/len(loader):.4f}")

Epoch 1, Loss: 3.6660

KeyboardInterrupt:

In [47]:
n=1111

example_input = torch.tensor(np.stack(subset_df["one_hot"].values[n:n+1]), dtype=torch.float32)
example_output = torch.tensor(np.stack(subset_df["pfam_one_hot"].values[n:n+1]), dtype=torch.float32)

output = model(example_input)

# print all values in the output tensor into console
output = output.view(-1, output.shape[-1])  # flatten for easier viewing
output = output.argmax(axis=-1)  # get the predicted class indices

print(output.shape)
print(output)

# Convert output to numpy array for easier viewing
example_output = example_output.view(-1, example_output.shape[-1])  # flatten for easier viewing
example_output = example_output.argmax(axis=-1)  # get the true class indices
print(example_output.shape)
print(example_output)

# output = output.detach().numpy()

# print(list(output))

# print values at these indexes

torch.Size([100])
tensor([326, 326, 326, 326,   0,   0,   0,   0,   0,   0,   0, 479, 326, 326,
        326, 326, 326, 326, 326, 326, 326, 407, 407, 326, 170, 242, 407, 407,
        467, 614,   0, 371,   0,  98,  98,  98,  98,  22,  22, 111, 111,   0,
        564, 564,  22, 157,  39,  39,  98,  98,  22, 326, 453,  39, 602, 174,
        127, 127, 403, 157, 524, 111,  98, 293, 149,  98, 242, 326, 326,  98,
         98,  98, 326, 561, 326, 539, 539, 539, 242, 539, 539, 372, 326, 326,
        242, 564, 358, 358, 358, 358, 349, 326, 326, 122, 326, 326, 326, 326,
          0,   0])
torch.Size([100])
tensor([326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326,
        326, 326, 326, 326, 326, 326, 326, 184, 184, 184, 184, 184, 184, 184,
        184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184,
        184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184,
        184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184,
        184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184,
        184, 184, 184, 184, 184, 184, 326, 326, 326, 326, 326, 326, 326, 326,
        326, 326])

In [48]:
print([int(i) for i in output.numpy()])
print([int(i) for i in example_output.numpy()])

[326, 326, 326, 326, 0, 0, 0, 0, 0, 0, 0, 479, 326, 326, 326, 326, 326, 326, 326, 326, 326, 407, 407, 326, 170, 242, 407, 407, 467, 614, 0, 371, 0, 98, 98, 98, 98, 22, 22, 111, 111, 0, 564, 564, 22, 157, 39, 39, 98, 98, 22, 326, 453, 39, 602, 174, 127, 127, 403, 157, 524, 111, 98, 293, 149, 98, 242, 326, 326, 98, 98, 98, 326, 561, 326, 539, 539, 539, 242, 539, 539, 372, 326, 326, 242, 564, 358, 358, 358, 358, 349, 326, 326, 122, 326, 326, 326, 326, 0, 0]
[326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 184, 326, 326, 326, 326, 326, 326, 326, 326, 326, 326]

In [61]:
n = 90

example_input = torch.tensor(np.stack(subset_df["one_hot"].values[n:n+1]), dtype=torch.float32)
example_output = torch.tensor(np.stack(subset_df["pfam_one_hot"].values[n:n+1]), dtype=torch.float32)

# Get raw output from model
raw_output = model(example_input)

# Flatten for easier viewing
raw_output_flat = raw_output.view(-1, raw_output.shape[-1])
predicted_indices = raw_output_flat.argmax(axis=-1)

# Print shape and predicted indices
print("Predicted class indices:", predicted_indices.shape)
print(predicted_indices)

# Print the actual values that argmax selected
predicted_values = raw_output_flat[torch.arange(raw_output_flat.shape[0]), predicted_indices]
print("Values selected by argmax:", predicted_values)

# For the true labels
example_output_flat = example_output.view(-1, example_output.shape[-1])
true_indices = example_output_flat.argmax(axis=-1)
print("True class indices:", true_indices.shape)
print(true_indices)

# If desired: values selected in ground truth as well (normally one-hot encoded so should be 1.0)
true_values = example_output_flat[torch.arange(example_output_flat.shape[0]), true_indices]
print("True values from one-hot:", true_values)

Predicted class indices: torch.Size([100])
tensor([314, 314, 314, 314, 391, 391, 391, 391, 391, 391, 394, 394, 394, 394,
        394, 394, 394, 394, 394, 394, 394, 394, 394, 394, 394, 394, 394, 394,
        149, 472, 472, 472, 472, 472, 472, 472, 472, 472, 472, 472, 472, 472,
        472, 472, 472,   3,   3, 314, 314, 314, 314, 314, 314, 314, 314, 314,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  50])
Values selected by argmax: tensor([ 7.4277,  7.3095,  8.2424,  7.2051,  8.4760, 11.4314,  9.3244,  8.5534,
         8.4048, 10.7787, 12.2779, 15.0474, 15.1132, 16.4672, 14.4989, 14.3691,
        11.8976, 15.2778, 15.9507, 13.6095, 10.8907,  7.7734,  9.9249, 14.2727,
        15.3568, 12.3570,  8.4824,  3.9467,  2.3888,  2.3025,  3.0961,  3.5697,
         3.1835,  6.9824,  6.9600,  8.3402,  8.5924,  9.7201, 10.1630, 10.4229,
         9.5074,  8.0477,  6.5238,  4.3185,  3.9544,  1.8556,  1.5471,  3.0511,
        11.3624, 17.0569, 21.4774, 22.9721, 25.3508, 23.5753, 18.1089,  9.6925,
        14.1834, 20.8827, 22.5169, 22.2735, 22.8822, 24.0929, 24.6563, 24.8643,
        24.9101, 24.9112, 24.9112, 24.9112, 24.9112, 24.9112, 24.9112, 24.9112,
        24.9112, 24.9112, 24.9112, 24.9112, 24.9112, 24.9112, 24.9112, 24.9112,
        24.9112, 24.9112, 24.9112, 24.9112, 24.9112, 24.9112, 24.9112, 24.9112,
        24.9112, 24.9112, 24.9112, 24.9167, 24.9176, 24.9998, 25.0558, 25.2017,
        23.8646, 20.6122, 12.3922,  6.1838], grad_fn=<IndexBackward0>)
True class indices: torch.Size([100])
tensor([314, 314, 314, 314, 314, 472, 472, 472, 472, 472, 472, 472, 472, 472,
        472, 472, 472, 472, 472, 472, 472, 472, 472, 472, 472, 472, 472, 472,
        472, 472, 472, 472, 472, 472, 472, 472, 472, 472, 472, 472, 472, 472,
        472, 472, 472, 472, 472, 472, 314, 314, 314, 314, 314, 314, 314,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0])
True values from one-hot: tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
example_output = torch.tensor(np.stack(subset_df["pfam_one_hot"].values[11:12]), dtype=torch.float32)

example_output = example_output.view(-1, example_output.shape[-1])  # flatten for easier viewing
example_output = example_output.argmax(axis=-1)  # get the true class indices
print(example_output.shape)
print(example_output)

torch.Size([100])
tensor([314, 314, 314, 314, 314, 314, 314, 441, 441, 441, 441, 441, 441, 441,
        441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441,
        441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441,
        441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441,
        441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441,
        441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441, 441,
        441, 441, 314, 314, 314, 314,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0])

In [32]:
np.set_printoptions(threshold=10_000)
torch.set_printoptions(profile="full")

example_output = torch.tensor(np.stack(subset_df["pfam_one_hot"].values[11:12]), dtype=torch.float32)
print(example_output)

example_output = example_output.view(-1, example_output.shape[-1])  # flatten for easier viewing
example_output = example_output.argmax(axis=-1)  # get the true class indices

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [38]:
import hashlib

def tensor_hash(tensor: torch.Tensor) -> str:
    # Ensure tensor is on CPU and in a consistent dtype
    tensor = tensor.detach().cpu()
    # Convert to contiguous bytes
    tensor_bytes = tensor.numpy().tobytes()
    # Compute SHA-256 hash
    return hashlib.sha256(tensor_bytes).hexdigest()

In [40]:
tmp = torch.tensor(np.stack(subset_df["pfam_one_hot"].values[12:13]), dtype=torch.float32)

tensor_hash(tmp)

'deb3028ba7b32029ab99ec5199561004bfca9dfae2e4071e0c056a636e5e0ebd'